### ISSUE TITLE
Why this module when there is already a `koa-compress`?

### ISSUE THREAD

**Issue by ktmud** [koajs/koa-gzip#2]
https://github.com/koajs/compress

**Comment by dj-hedgehog** [comment]
Bumping this up again. Both koa-gzip and koa-compress need some love in the light of the koa v2 development but which one should we actually use?

**Comment by coderhaoxin** [comment]
> need some love in the light of the koa v2 

For now, you can use https://github.com/gyson/koa-convert

**Comment by dj-hedgehog** [comment]
We're using `koa-gzip` along other middlewares for our framework strapi and track the v2 transition of all our middleware here https://github.com/wistityhq/strapi/issues/41

There's always `koa-convert` but we also strive to push the general koa development forward and therefore I'm also turning to the middleware authors to initiate the transition or ask whether they are willing to accept PRs.

So would you accept a PR?

**Comment by jonathanong** [comment]
should we deprecate this in favor of compress?

**Comment by dead-horse** [comment]
don't have the rights to deprecate this package in npm. @fengmk2

**Comment by fengmk2** [comment]
deprecated on npm now.
